### PR TITLE
Feat::snake:Created views

### PR DESCRIPTION
**Pull request by Nextafari**
## Description
Please include a summary of the change and relevant motivation and context. 
List any dependencies that are required for this change.
Created views for the project

All pull requests should be related to open issues. Indicate the issue(s) bellow and remove this line:
Fixes #(issue number 1) #(issue number 2 if applicable)

## How Has This Been Tested?
Please describe in detail how you tested your changes.
Include details of your testing environment, and the tests you ran to see how your change affects other areas of the code etc.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by belloshehu** [comment]
Nice work! However, it is suggested you make the following changes:

*The proper workflow is to merge your changes into backend branch locally before merging to fullstack remotely through pull request.

* Project level urls.py is overpopulated with urls pattern from fullstack application alone.  As solution, create another urls.py in the application directory where your views.py resides and add all the url patterns for the fullstack application. You can then include the application level urls.py in urlpattern list in the project level urls.py as follows:

urlpattern = [
        path(' ', include('fullstack.urls'))
]

**Comment by Nextafari** [comment]
Hello Mr Bello,
I hope this meets you well, I have duly noted your review and I will do so once I have juice on my pc to do so.
Kind regards.

**Comment by ifelajulo** [comment]
Juice on your pc i do not understand be a little bit explicit

**Comment by Nextafari** [comment]
My laptop is out of battery, I don’t have power to recharge my battery, I’d be able to turn on my generator much later in the day.

**Pull request closed without merging**
